FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["Polyclinic.API/Polyclinic.API.csproj", "Polyclinic.API/"]
COPY ["Polyclinic.Infrastructure/Polyclinic.Infrastructure.csproj", "Polyclinic.Infrastructure/"]
COPY ["Polyclinic.Application/Polyclinic.Application.csproj", "Polyclinic.Application/"]
COPY ["Polyclinic.Domain/Polyclinic.Domain.csproj", "Polyclinic.Domain/"]
RUN dotnet restore "Polyclinic.API/Polyclinic.API.csproj"
COPY . .
WORKDIR "/src/Polyclinic.API"
RUN dotnet build "Polyclinic.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Polyclinic.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Polyclinic.API.dll"]